model:
  architecture: "DANN_DenseNet121"
  num_classes: 13  # Excluding support devices for task classification
  domain_classes: 1  # Binary domain classification
  freeze_backbone: true

training:
  batch_size: 64
  max_epochs: 15
  attention_learning_rate: 1e-3
  learning_rate: 1e-4
  weight_decay: 1e-5
  factor: 0.005
  strategy: 'task_entropy' #or 'schedule'
  
data:
  image_size: 224
  resize: [256, 256]
  policy: "u-ones-lsr"

paths:
  train_csv: "/home/nguyentk/diancxr/dataset/versions/1/train.csv" #Replace with your own path
  valid_csv: "/home/nguyentk/diancxr/dataset/versions/1/valid.csv" #Replace with your own path
  test_csv: "/home/nguyentk/diancxr/dataset/chestxpert-testset/content/chexlocalize/chexlocalize/CheXpert/test_labels.csv" #Replace with your own path
  train_base: "/home/nguyentk/diancxr/dataset/versions/1" #Replace with your own path
  valid_base: "/home/nguyentk/diancxr/dataset/versions/1" #Replace with your own path
  test_base: "/home/nguyentk/diancxr/dataset/chestxpert-testset/content/chexlocalize/chexlocalize/CheXpert" #Replace with your own path

class_names:
  - "No Finding"
  - "Enlarged Cardiomediastinum"
  - "Cardiomegaly"
  - "Lung Opacity"
  - "Lung Lesion"
  - "Edema"
  - "Consolidation"
  - "Pneumonia"
  - "Atelectasis"
  - "Pneumothorax"
  - "Pleural Effusion"
  - "Pleural Other"
  - "Fracture"
  - "Support Devices"